Professional skills progress bar #9
front-end-by-rimantas/10-grupe-portfolio-arika pull request #27
Opened 2019-09-25 12:45 UTC by Dialiu

2019-09-25 13:19 UTC, belauzas requested changes

2019-09-25 13:19 UTC, belauzas commented on css/progress-bar.css
> +
Būtų galima pridėti bent minimalų stiliu, pvz:
```
display: inline-block;
width: 100%;
```

2019-09-25 15:52 UTC, RenataValanciute approved these changes

2019-09-25 15:53 UTC, RenataValanciute approved these changes

2019-09-25 15:53 UTC, RenataValanciute approved these changes

2019-09-25 15:54 UTC, RenataValanciute submitted a review, later dismissed

2019-09-25 17:20 UTC, RenataValanciute submitted a review, later dismissed

2019-09-26 15:20 UTC, belauzas requested changes
Please....

2019-09-26 15:20 UTC, belauzas commented on css/progress-bar.css
> +            right: 0;
Ar tikrai čia geriausia taktika pozicionuoti skaitinę reikšmę?

2019-09-26 15:20 UTC, belauzas commented on js/functions.js
> +        skill.title > 50 ||
Ar toks pavadinimo limitas yra protingas ir apgalvotas?

2019-09-27 12:24 UTC, RenataValanciute requested changes
Progres baras turetu uzsikrauti tik tada kai iki jo nuscrolini ir jie uzsikrauna ne visi iskart, o po viena

2019-10-02 20:27 UTC, RenataValanciute submitted a review, later dismissed

2019-10-02 20:31 UTC, RenataValanciute submitted a review, later dismissed

2019-10-02 21:34 UTC, belauzas commented
Panašu, jog kodas neveikia 😔
"functions.js" faile yra sintaksės klaidų, bei "actions.js" sako, jog nežino tokios funkcijos kaip "renderAchievements"

2019-10-05 09:19 UTC, belauzas submitted a review, later dismissed
LGTM

2019-10-06 13:08 UTC, RenataValanciute approved these changes

2019-10-06 13:08 UTC, merged