Heroes
front-end-by-rimantas/10-grupe-portfolio-arika pull request #31
Opened 2019-09-28 17:24 UTC by RenataValanciute

2019-10-02 21:36 UTC, belauzas requested changes
Hero dalies fonas turėtų būti per visą ekrano plotį

2019-10-04 16:29 UTC, Evgeniya-SS approved these changes

2019-10-04 16:35 UTC, Evgeniya-SS submitted a review, later dismissed

2019-10-05 09:02 UTC, belauzas approved these changes
LGTM

2019-10-05 09:04 UTC, merged